### ISSUE TITLE
"gmn select" fails on versions with build = 0

### ISSUE THREAD

**Issue by olithissen** [jangraefen/go-man#22]
**Describe the bug**
`gmn install 1.16` successfully downloads and unpacks go1.16.0 to _GMNROOT\go1.16_ but `gmn select 1.16` fails

**To Reproduce**
1. run `gmn install 1.15.8` -> installed to go1.15.8 -> _go-default_ linked to _go1.15.8_
2. run `gmn install 1.16` -> installed to go1.16 -> _go-default_ still linked to _go1.15.8_
3. run `gmn select 1.16` fails with "version 1.16.0 was not found"
4. run `gmn select 1.16.0` fails with "version 1.16.0 was not found"

**Expected behavior**
* `gmn select 1.16` should set _go-default_ to according version
* `gmn select 1.16` and `gmn select 1.16.0` could be treated as equivalent

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows-amd64
 - Version: gmn0.3.1.windows-amd64.zip

**Comment by jangraefen** [comment]
Thanks for the report and the analysis @olithissen. I found the issue quickly, with the help of your information.
A fixed version is released as `v0.3.2`.
